list: $/pixinside/navigation/models/navigation/columns.yaml
modelClass: Pixinside\Navigation\Models\Navigation
title: Navigations
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pixinside/navigation/navigations/update/:id'
